# Generated by Django 6.0.2 on 2026-03-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('annual_reading_goal', models.IntegerField(default=0)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=20)),
                ('show_reading_activity', models.BooleanField(default=True)),
                ('allow_others_see_shelves', models.BooleanField(default=True)),
                ('allow_others_see_stats', models.BooleanField(default=True)),
                ('username_changes_count', models.IntegerField(default=0)),
                ('last_username_change_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
